---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-poc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-infrastructure-poc
  source:
    repoURL: https://github.com/sahmed-ssc-spc/poc-s3-bucket.git
    targetRevision: HEAD
    path: controller
  destination:
    server: https://kubernetes.default.svc
    namespace: production-poc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true