---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev4-sandbox-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: This project contains all resouces deployed into Dev4-Sanbox
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'